### PR TITLE
slide show on homepage index.html

### PR DESCRIPTION
**Pull request by jaesow**

### CODE REVIEW

**Comment by jaesow** [comment]
slight changes to text/nav bar. temporary photos. will come back to fix and finish

**Comment by jaesow** [comment]
deleted demo styling pages

**Comment by jaesow** [comment]
will also come back to separate script from html once everything is as it should be

**Review by UrviA — APPROVED** [review]
I think you should move the script out into a separate file but otherwise it looks good.

**Comment by UrviA** [comment]
I didn't notice this earlier but the indentation on index.html is all off. Would be helpful if you fixed it!

**Pull request merged**
