### PR TITLE
added stats page servlet

### PR DESCRIPTION
**Pull request by blumejr26**
added stats servlet; servlet prints a hard-coded message when user request localhost:8080/stats

### CODE REVIEW

**Comment by blumejr26** [comment]
Also went ahead and added the stats page datastore; this returns the total number of messages (up to a max of 1000) that the queried user has posted.

**Comment by blumejr26** [comment]
Went ahead and completed the unguided project.  I may go back in add functionality to the stats.html page (I put in comments for placeholders).  Gonna be a little busy this weekend taking care of my very sick 3yo.

**Comment by UrviA** [comment]
Looks good! 
In your updates to Datastore.java in your 2nd commit, you replaced some imports with an 'import ....*'. I think it makes it a little less clear what we're actually using considering we only need to import very few things out of the many that com.google.appengine.api.datastore really has.

(also, doesn't this cause potential namespace collisions?)

**Review by UrviA — COMMENTED** [review]
In your changes to Datastore.java, you've replaced some imports with "import com.....*". I think this makes it very unclear what we're actually using considering we need to import only a few things from the very extensive package.
(Also, doesn't this cause potential namespace collisions?)

Other than that, this looks good! Let me know your opinion on this change!

**Comment by blumejr26** [comment]
I may have been half asleep when do those changes, I’ll re-look at it when I get back from the hospital and verify that there’s no potential collisions or possible fatal errors

**Comment by UrviA** [comment]
I personally like listing out the packages instead of importing everything in cases like this regardless of collisions but I suppose that's more a matter of preference if it isn't causing any errors.

**Comment by blumejr26** [comment]
You know looking at it, I don’t remember making any changes to the header files, I only added in the code for the stats data store; I wonder how those headers got deleted, because it’s obviously saying I deleted them? Weird.

**Review by blumejr26 — COMMENTED** [review]
replaced the missing import files in the datastore.java file

**Review by UrviA — APPROVED** [review]
yep header files look good now!

**Pull request merged**
